console.log(typeof(100));
console.log(typeof(73.9));
console.log(typeof(NaN));
console.log(typeof("Water"));
console.log(typeof(false));
console.log( typeof(9 != 11));
console.log("Orang" + "e");
console.log("Orange" - "s");
console.log("4" + "8");
console.log( "4" - "8");
console.log( "name" + 3);
console.log( "name" - 3);
console.log(82 * "word");
console.log( 1 + "hello");
console.log( "hello" + 1);
console.log( 1 + true);
console.log("hello" + true);
console.log(typeof (Infinity));
console.log( 1 == '1');
console.log(1 === '1');